import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: { default: '연지 기술 블로그', template: '%s | Yoohunn' },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>{children}</body>
    </html>
  );
}
